---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.5.1

platforms:
- name: windows-2012r2
  transport:
    name: winrm
    elevated: true
    elevated_username: System
    elevated_password: null
  driver_config:
    box: opentable/win-2012r2-standard-amd64-nocm
    box_url: http://filer.criteo.prod/boxes/criteo-windows-2012r2-standard.box

suites:
- name: default
  run_list:
  - recipe[ms_dotnet::ms_dotnet4]
  attributes:
    ms_dotnet:
      v4:
        version: 4.6.1
