---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[solodev_sensu::rabbitmq]
      - recipe[solodev_sensu::client]
    attributes:
