---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[solodev_sensu::rabbitmq]
      - recipe[solodev_sensu::rabbitmq_leader]
      - recipe[solodev_sensu::client]
